    application dev {
      live on;
      meta copy;
      hls on;
      hls_path /tmp/dev;

      record all;
      record_path /home/www/video_recordings;
      record_suffix -%d-%b-%y-%T.flv;
    }