    application dev {
      live on;
      meta copy;
      hls on;
      hls_path /tmp/dev;

	  #push to endpoint connected to site
	  push rtmp://localhost/hls/;

      # YouTube
      push rtmp://a.rtmp.youtube.com/live2/6p0u-2e65-dkv8-6uwq-ac6z;

      record all;
      record_path /home/www/video_recordings;
      record_suffix -%d-%b-%y-%T.flv;
    }