    application dev {
      live on;
      meta copy;
      hls on;
      hls_path /tmp/dev;

	  #push to endpoint connected to site
	  push rtmp://localhost/hls/;

      # YouTube
      push rtmp://a.rtmp.youtube.com/live2/6p0u-2e65-dkv8-xxxxxxxx-ac6z;
	  
	  #twitch
	  push rtmp://ord03.contribute.live-video.net/app/live_xxxxxxxxxx_74uCAU5d6jymimTguhAdZd27qt0Hxa;

      record all;
      record_path /home/www/video_recordings;
      record_suffix -%d-%b-%y-%T.flv;
    }